const vertexArr = [
  'Ymir',
  'Borr',
  'Bestla',
  'Odin',
  'Frigg',
  'Thor',
  'Baldr',
  'Loki',
  'Hel',
  'Jörmungandr',
  'Fenrir',
  'Sif',
  'Váli',
  'Vidar',
  'Njord',
  'Skadi',
  'Freyr',
  'Freyja',
  'Tyr',
  'Höðr',
  'Rindr',
  'Forseti',
  'Hermod',
  'Bragi',
  'Idunn',
  'Aegir',
  'Ran',
  'Höenir',
  'Angrboda',
  'Nanna',
  'Sigyn',
  'Narvi',
  'Vili',
  'Ve',
  'Thrym',
  'Hymir',
  'Gerd',
  'Aurboda',
  'Gymir',
];

const edgeArr = [
  ['Ymir', 'Borr'],
  ['Borr', 'Odin'],
  ['Borr', 'Vili'],
  ['Borr', 'Ve'],
  ['Bestla', 'Odin'],
  ['Bestla', 'Vili'],
  ['Bestla', 'Ve'],
  ['Odin', 'Thor'],
  ['Odin', 'Baldr'],
  ['Odin', 'Váli'],
  ['Odin', 'Vidar'],
  ['Odin', 'Höðr'],
  ['Odin', 'Hermod'],
  ['Odin', 'Bragi'],
  ['Frigg', 'Baldr'],
  ['Frigg', 'Hermod'],
  ['Loki', 'Hel'],
  ['Loki', 'Jörmungandr'],
  ['Loki', 'Fenrir'],
  ['Loki', 'Narvi'],
  ['Angrboda', 'Hel'],
  ['Angrboda', 'Jörmungandr'],
  ['Angrboda', 'Fenrir'],
  ['Sigyn', 'Narvi'],
  ['Sif', 'Thor'],
  ['Njord', 'Freyr'],
  ['Njord', 'Freyja'],
  ['Skadi', 'Freyr'],
  ['Skadi', 'Freyja'],
  ['Rindr', 'Váli'],
  ['Baldr', 'Forseti'],
  ['Nanna', 'Forseti'],
  ['Idunn', 'Bragi'],
  ['Aegir', 'Ran'],
  ['Thrym', 'Hymir'],
  ['Aurboda', 'Gerd'],
  ['Gymir', 'Gerd'],
];
